# ERROR: 40
# WARNING: 30
# INFO: 20
# DEBUG: 10
log_level: 10
log_file_path: /path/to/log/file.log

port: 9001

host: http://localhost:9200
http_scheme: http
verify_ssl: false

service: es
aws_region: us-west-2
